version: 2
updates:
    - package-ecosystem: npm
      directory: "/express/backend"
      schedule:
          interval: daily
          time: "04:00"
          timezone: Europe/Berlin
      allow:
          - dependency-name: "@iobroker/create-adapter"
            dependency-type: "all"
          - dependency-name: "@iobroker/repochecker"
            dependency-type: "all"
      open-pull-requests-limit: 20
      assignees:
          - UncleSamSwiss
      versioning-strategy: increase

    - package-ecosystem: npm
      directory: "/express/frontend"
      schedule:
          interval: daily
          time: "04:00"
          timezone: Europe/Berlin
      allow:
          - dependency-name: "@iobroker/create-adapter"
            dependency-type: "all"
      open-pull-requests-limit: 20
      assignees:
          - UncleSamSwiss
      versioning-strategy: increase
