name: Publish Docker Image

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

jobs:
    docker:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Write Git Info to Code
              run: |
                  echo "export const GIT_COMMIT = \"$(git rev-parse --short HEAD)\", GIT_BRANCH = \"$(git branch --show-current)\";" > express/backend/src/version.ts
                  echo "export const GIT_COMMIT = \"$(git rev-parse --short HEAD)\", GIT_BRANCH = \"$(git branch --show-current)\";" > express/frontend/src/version.ts

            - name: Build and push
              uses: docker/build-push-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: iobroker/dev-portal/express
                  path: ./express
                  tag_with_ref: true
                  tag_with_sha: true
